{% set name = "python-calamine" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_calamine-{{ version }}.tar.gz
  sha256: 67dd1ac95e10c7737c1b2e43d6b6a9c1e3bbf615ee5e866ca927d94e04e5e4c0

build:
  script:
    # PyPy has weird sysconfigdata name
    - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1,<2                         # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python
    - packaging >=24.1

test:
  imports:
    - python_calamine
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dimastbk/python-calamine
  dev_url: https://github.com/dimastbk/python-calamine
  summary: Python binding for Rust's library for reading excel and odf file - calamine.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dimastbk
