{% set name = "python-calamine" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_calamine-{{ version }}.tar.gz
  sha256: c1ad3f80aaf1e0b54da1b85790f19c8a146cad75c07c95baf76d4fb56a0ec632

build:
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<1.1
  run:
    - python

test:
  imports:
    - python_calamine
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dimastbk/python-calamine
  dev_url: https://github.com/dimastbk/python-calamine
  summary: Python binding for Rust's library for reading excel and odf file - calamine.
  license: MIT
  license_file: 
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dimastbk
