schema_version: 1

context:
  version: "0.8.3"

package:
  name: python-calamine
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-calamine/python_calamine-${{ version }}.tar.gz
  sha256: 93dba488baad15bb2daed4bf45007ec550a3905aa4d39f764d1573290b72961c

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python

tests:
  - python:
      imports:
        - python_calamine
      pip_check: true
  - files:
      source:
        - tests/
    requirements:
      run:
        - pandas
        # from pandas[excel]
        - openpyxl
        - pyxlsb
        - xlrd
        - pytest
    script:
      - pytest

about:
  summary: Python binding for Rust's library for reading excel and odf file - calamine.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/dimastbk/python-calamine
  repository: https://github.com/dimastbk/python-calamine

extra:
  recipe-maintainers:
    - dimastbk
    - mgorny
